/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.hopital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wdiac
 */
public class DIAGNOSTIQUE extends javax.swing.JFrame {

    /**
     * Creates new form DIAGNOSTIQUE
     */
    public DIAGNOSTIQUE() {
        initComponents();
        GetPatient();
        GetName();
        AfficherDiagnostique();
        GetMedecins();
    }
    

    private void GetPatient(){
        try{
         Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB","User1","root");
         String query = "SELECT * FROM PatientTABLE"; 
         PreparedStatement cmd = connection.prepareStatement(query);   
         ResultSet RS = cmd.executeQuery();
             
         while(RS.next()){
             String MypatId = RS.getString("PATID");
             PatIdCBox.addItem(MypatId);
         }
         RS.close();
         connection.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
   private void GetName() {
    try {
        Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB", "User1", "root");
        String query = "SELECT * FROM PatientTABLE WHERE PATID=?";
        PreparedStatement cmd = connection.prepareStatement(query);
        cmd.setString(1, PatIdCBox.getSelectedItem().toString());
        ResultSet RS = cmd.executeQuery();

        if (RS.next()) { // Utilisez if au lieu de while
            String myPatName = RS.getString("PATName");
            PatNameBox.setText(myPatName);
        } else {
            PatNameBox.setText(""); // Réinitialisez le champ si aucun résultat n'est trouvé
        }

        RS.close();
        cmd.close();
        connection.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
    private void AfficherDiagnostique(){
          try{
       DefaultTableModel model = (DefaultTableModel) DiagnostiqueTable.getModel();
      model.setRowCount(0);
       Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB","User1","root");

       String query = "SELECT * FROM DIAGNOSTIQUETABLE"; 
       Statement cmd = connection.createStatement();
       ResultSet rs = cmd.executeQuery(query);

       while (rs.next()) {
                String DIAGID = rs.getString("DIAGID");
                String PATID = rs.getString("PATID");
                String PATNAME= rs.getString("PATNAME");
                String SYMPTOMES= rs.getString("SYMPTOMES");
                String DIAGNOSTIQUE= rs.getString("DIAGNOSTIQUE");
                String MEDECIN= rs.getString("MEDECIN");

                model.addRow(new Object[]{DIAGID, PATNAME,PATID ,SYMPTOMES ,DIAGNOSTIQUE, MEDECIN});
            }

            connection.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        Homepagelink = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DiagBox = new javax.swing.JTextField();
        DIAGID = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PatNameBox = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PatientSummary = new javax.swing.JTextArea();
        PatIdCBox = new javax.swing.JComboBox<>();
        PrintBtn = new javax.swing.JButton();
        SymptomesBox = new javax.swing.JTextField();
        MedBox = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DiagnostiqueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        Homepagelink.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Homepagelink.setForeground(new java.awt.Color(255, 255, 255));
        Homepagelink.setText("Systeme de Gestion d'Hopital");
        Homepagelink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomepagelinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(Homepagelink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Homepagelink, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("DIAGNOSTIQUES INFORMATION");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("SYMPTOMES");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("NAME");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("DIAGNOSTIQUES");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("ID");

        AddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddBtn.setText("Ajouter");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UpdateBtn.setText("Modifier");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtn.setText("Supprimer");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Effacer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("PATID");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("MEDECINES");

        PatientSummary.setColumns(20);
        PatientSummary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PatientSummary.setRows(5);
        PatientSummary.setText("    ===========Patient Summary==========");
        jScrollPane1.setViewportView(PatientSummary);

        PatIdCBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PatIdCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatIdCBoxActionPerformed(evt);
            }
        });

        PrintBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PrintBtn.setText("Imprimer");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        MedBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MedBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedBoxMouseClicked(evt);
            }
        });
        MedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DIAGID, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(PatNameBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(PatIdCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DiagBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(SymptomesBox, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(MedBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SymptomesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DiagBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DIAGID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PatNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PatIdCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddBtn)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeleteBtn)
                        .addComponent(jButton4)
                        .addComponent(UpdateBtn)
                        .addComponent(PrintBtn)))
                .addGap(18, 18, 18))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PATIENTS LIST");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(397, 397, 397)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        DiagnostiqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Diagnostique ID", "PatientName", "PatientID", "Symptomes", "Diagnostiques", "Medecins"
            }
        ));
        DiagnostiqueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiagnostiqueTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DiagnostiqueTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void GetMedecins(){
     try {
        Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB", "User1", "root");
        String query = "SELECT * FROM DoctorTABLE";
        Statement cmd = connection.createStatement();
        
        ResultSet RS = cmd.executeQuery(query);

        while(RS.next()) { // Utilisez if au lieu de while
            String myPatName = RS.getString("DocName");
            MedBox.addItem(myPatName);
            
        }

        RS.close();
        cmd.close();
        connection.close();
    } catch (Exception ex) {
        ex.printStackTrace();
    }
}
    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
       if(DIAGID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Veuillez selectionner l'ID à supprimé");
        }try{
            Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB","User1","root");
            String query = "DELETE FROM DIAGNOSTIQUETABLE WHERE DIAGID=?";
            PreparedStatement cmd = connection.prepareStatement(query);
            cmd.setString(1,DIAGID.getText());
            cmd.executeUpdate();
            JOptionPane.showMessageDialog(this, "Diagnostique supprimé");
            connection.close();
            AfficherDiagnostique();
                          
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
       if(DIAGID.getText().isEmpty()|| PatNameBox.getText().isEmpty() || SymptomesBox.getText().isEmpty() || DiagBox.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Informations manquantes");

        }else{
               
        try{
           DefaultTableModel model = (DefaultTableModel) DiagnostiqueTable.getModel();
              Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB","User1","root");
              String query = "UPDATE DIAGNOSTIQUETABLE SET PATNAME=?, PATID=?, SYMPTOMES=? ,DIAGNOSTIQUE=?, MEDECIN=? WHERE DIAGID=?";            
              PreparedStatement cmd = connection.prepareStatement(query);
              
               cmd.setString(1, PatNameBox.getText());
               cmd.setString(2, PatIdCBox.getSelectedItem().toString());
               cmd.setString(3, SymptomesBox.getText());
               cmd.setString(4,DiagBox.getText());
               cmd.setString(5,MedBox.getSelectedItem().toString());
               cmd.setString(6, DIAGID.getText());
               cmd.executeUpdate();
               JOptionPane.showMessageDialog(this, "Diagnostique modifié avec succès");
               connection.close();
               AfficherDiagnostique();
               }
        catch(Exception ex){
ex.printStackTrace();
}}
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
 if(DIAGID.getText().isEmpty()|| PatNameBox.getText().isEmpty() || SymptomesBox.getText().isEmpty() || DiagBox.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Informations manquantes");

        }else{
        try{
           
                  Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/HospitalJavaDB","User1","root");

           String query = "INSERT INTO DIAGNOSTIQUETABLE VALUES(?,?,?,?,?,?)";
           PreparedStatement cmd = connection.prepareStatement(query);
           cmd.setInt(1,Integer.valueOf( DIAGID.getText()));
           cmd.setString(2, PatIdCBox.getSelectedItem().toString());
           cmd.setString(3,PatNameBox.getText());
           cmd.setString(4, SymptomesBox.getText());
           cmd.setString(5, DiagBox.getText());
           cmd.setString(6, MedBox.getSelectedItem().toString());
           cmd.executeUpdate();
           JOptionPane.showMessageDialog(this, "Diagnostique inséré avec succès");
           connection.close();
           AfficherDiagnostique();

        }catch(Exception ex){
            ex.printStackTrace();
        }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       DIAGID.setText("");      
       PatNameBox.setText("");
       SymptomesBox.setText("");
       DiagBox.setText("");
       MedBox.setSelectedIndex(0);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void DiagnostiqueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiagnostiqueTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) DiagnostiqueTable.getModel();
        int myindex = DiagnostiqueTable.getSelectedRow();
        DIAGID.setText((String) model.getValueAt(myindex, 0));  
        PatNameBox.setText((String) model.getValueAt(myindex, 1));
       PatIdCBox.setSelectedItem(model.getValueAt(myindex, 2));
       SymptomesBox.setText((String) model.getValueAt(myindex, 3));
        DiagBox.setText((String) model.getValueAt(myindex, 4));        
        MedBox.setSelectedItem((String) model.getValueAt(myindex, 5));
        PatientSummary.setText("  ===========Patient Summary=========="+"\n"+"\n"+"PatientName:"+PatNameBox.getText()+"\n"+"\n"+"Symptomes:"+SymptomesBox.getText()+"\n"+"\n"+"Diagnostique:"+DiagBox.getText()+"\n"+"\n"+"Medecins:"+MedBox.getSelectedItem());
 

    }//GEN-LAST:event_DiagnostiqueTableMouseClicked

    private void HomepagelinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomepagelinkMouseClicked
        new HomeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomepagelinkMouseClicked

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void PatIdCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatIdCBoxActionPerformed
        
        GetName();
        
    }//GEN-LAST:event_PatIdCBoxActionPerformed

    private void MedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedBoxActionPerformed

    private void MedBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedBoxMouseClicked
        
    }//GEN-LAST:event_MedBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSTIQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSTIQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSTIQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DIAGNOSTIQUE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DIAGNOSTIQUE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField DIAGID;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JTextField DiagBox;
    private javax.swing.JTable DiagnostiqueTable;
    private javax.swing.JLabel Homepagelink;
    private javax.swing.JComboBox<String> MedBox;
    private javax.swing.JComboBox<String> PatIdCBox;
    private javax.swing.JTextField PatNameBox;
    private javax.swing.JTextArea PatientSummary;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTextField SymptomesBox;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
